name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Gradle & Android SDK
        uses: actions/cache@v4
        with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              /usr/local/lib/android/sdk
            key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-android-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Publish JUnit Test Results
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/*.xml'

      - name: Run Android Lint
        run: ./gradlew lint --no-daemon

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            args: >
              -Dsonar.projectKey=kkvarma9387_WeatherApp
              -Dsonar.organization=kkvarma9387
              -Dsonar.host.url=https://sonarcloud.io

      - name: Build Debug APK
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # âœ… Firebase distribution AFTER build (and after upload)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Write GCP service account key to file
        run: |
          echo '${{ secrets.GCP_SA_KEY_JSON }}' > $HOME/gcp-key.json

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV


      - name: Distribute APK to Firebase App Distribution
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
            --app "$FIREBASE_APP_ID" \
            --groups "qa" \
            --release-notes "CI build from GitHub Actions"
